# Generated by Django 3.1.14 on 2023-12-01 23:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Geolocalizacion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('latitud_ubicacion', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitud_ubicacion', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('hora', models.TimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('accion', models.TextField(blank=True, null=True)),
                ('autor', models.CharField(blank=True, max_length=254, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(blank=True, max_length=54, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TiposCalle',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(blank=True, max_length=54, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Viaje',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('anulado', models.BooleanField(blank=True, null=True)),
                ('motivo_anulado', models.CharField(blank=True, max_length=254, null=True)),
                ('hora_inicio', models.DateTimeField(blank=True, null=True)),
                ('hora_termino', models.DateTimeField(blank=True, null=True)),
                ('tipo_viaje', models.CharField(max_length=54)),
                ('cantidad_pasajeros', models.IntegerField(blank=True, null=True)),
                ('cod_viaje', models.CharField(max_length=24, unique=True)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('latitud_origen', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitud_origen', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('latitud_destino', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitud_destino', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('origen', models.CharField(blank=True, max_length=254, null=True)),
                ('destino', models.CharField(blank=True, max_length=254, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('tipo_destino', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='viaje_tdestino', to='Gestion_viajes.tiposcalle')),
                ('tipo_origen', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='viaje_torigen', to='Gestion_viajes.tiposcalle')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(blank=True, max_length=54, null=True)),
                ('run', models.IntegerField(blank=True, null=True, unique=True)),
                ('dv', models.CharField(blank=True, max_length=1, null=True)),
                ('apellido_p', models.CharField(blank=True, max_length=54, null=True)),
                ('apellido_m', models.CharField(blank=True, max_length=54, null=True)),
                ('genero', models.CharField(blank=True, max_length=254, null=True)),
                ('nombre_usu', models.CharField(blank=True, max_length=54, null=True, unique=True)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('edad', models.IntegerField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('prefijo', models.CharField(blank=True, max_length=14, null=True)),
                ('telefono', models.IntegerField(blank=True, null=True)),
                ('password', models.TextField(blank=True, null=True)),
                ('direccion', models.CharField(blank=True, max_length=254, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('tipo_calle', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Gestion_viajes.tiposcalle')),
            ],
        ),
        migrations.CreateModel(
            name='PrefijosPais',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('numero_prefijo', models.CharField(blank=True, max_length=14, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('pais', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Gestion_viajes.pais')),
            ],
        ),
    ]
