# Generated by Django 3.1.14 on 2023-12-02 01:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion_viajes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='prefijo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Gestion_viajes.prefijospais'),
        ),
    ]
