# Generated by Django 3.1.14 on 2023-12-02 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion_viajes', '0002_auto_20231201_2242'),
    ]

    operations = [
        migrations.CreateModel(
            name='TiposTarifa',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('tipo', models.IntegerField(blank=True, null=True)),
                ('nombre', models.CharField(blank=True, max_length=54, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tarifa',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('monto_tarifa', models.IntegerField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('tipo_tarifa', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Gestion_viajes.tipostarifa')),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('fecha_reserva', models.DateTimeField(blank=True, null=True)),
                ('origen', models.CharField(blank=True, max_length=254, null=True, unique=True)),
                ('destino', models.CharField(blank=True, max_length=54, null=True, unique=True)),
                ('cantidad_pasajeros', models.IntegerField(blank=True, null=True)),
                ('anulado', models.IntegerField(blank=True, null=True)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('motivo_anulacion', models.TextField(blank=True, null=True)),
                ('fecha_anulacion', models.DateTimeField(blank=True, null=True)),
                ('estado_reserva', models.IntegerField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('tarifa', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Gestion_viajes.tarifa')),
                ('tipo_destino', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reserva_tdestino', to='Gestion_viajes.tiposcalle')),
                ('tipo_origen', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reserva_torigen', to='Gestion_viajes.tiposcalle')),
            ],
        ),
    ]
