# Generated by Django 3.1.14 on 2023-12-02 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion_viajes', '0003_reserva_tarifa_tipostarifa'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
