# Generated by Django 3.1.14 on 2023-12-02 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion_viajes', '0005_auto_20231202_1511'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='prefijo',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Gestion_viajes.prefijospais'),
        ),
    ]
