# Generated by Django 3.1.14 on 2023-12-02 20:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion_viajes', '0007_auto_20231202_1726'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='ciudad',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Gestion_viajes.ciudad'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='comuna',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Gestion_viajes.comuna'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='latitud_destino',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='reserva',
            name='latitud_origen',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='reserva',
            name='longitud_destino',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='reserva',
            name='longitud_origen',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='reserva',
            name='numero_destino',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reserva',
            name='numero_origen',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reserva',
            name='region',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Gestion_viajes.region'),
        ),
    ]
