# Generated by Django 3.1.14 on 2023-12-03 00:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion_viajes', '0009_auto_20231202_1807'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ruta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('origen', models.CharField(blank=True, max_length=254, null=True)),
                ('numero_origen', models.IntegerField(blank=True, null=True)),
                ('destino', models.CharField(blank=True, max_length=54, null=True)),
                ('numero_destino', models.IntegerField(blank=True, null=True)),
                ('fecha_viaje', models.DateTimeField(blank=True, null=True)),
                ('anulado', models.IntegerField(blank=True, null=True)),
                ('motivo_anulacion', models.TextField(blank=True, null=True)),
                ('observacion', models.CharField(blank=True, max_length=254, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('tipo_tarifa', models.IntegerField(blank=True, null=True)),
                ('monto_tarifa', models.FloatField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('tipo_destino', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ruta_tdestino', to='Gestion_viajes.tiposcalle')),
                ('tipo_origen', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ruta_torigen', to='Gestion_viajes.tiposcalle')),
            ],
        ),
    ]
