# Generated by Django 3.1.14 on 2023-12-05 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion_viajes', '0011_auto_20231202_2348'),
    ]

    operations = [
        migrations.AddField(
            model_name='ruta',
            name='hora_viaje',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ruta',
            name='fecha_viaje',
            field=models.DateField(blank=True, null=True),
        ),
    ]
