# Generated by Django 3.1.14 on 2023-12-05 03:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion_viajes', '0012_auto_20231204_2215'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reclamo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('reclamacion', models.TextField(blank=True, null=True)),
                ('estado', models.IntegerField(blank=True, null=True)),
                ('anulado', models.IntegerField(blank=True, null=True)),
                ('motivo_anulacion', models.TextField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('autor', models.ForeignKey(blank=True, default=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Gestion_viajes.usuario')),
            ],
        ),
    ]
