# Generated by Django 3.1.14 on 2023-12-05 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion_viajes', '0016_auto_20231205_1147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reclamo',
            name='reserva',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reclamo',
            name='viaje',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
