# Generated by Django 3.1.14 on 2023-12-05 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion_viajes', '0018_auto_20231205_1322'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='tipo',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
