# Generated by Django 3.1.14 on 2023-12-05 21:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion_viajes', '0019_usuario_tipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Secretaria',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Taxista',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(blank=True, max_length=54, null=True)),
                ('apellido_p', models.CharField(blank=True, max_length=54, null=True)),
                ('apellido_m', models.CharField(blank=True, max_length=54, null=True)),
                ('genero', models.CharField(blank=True, max_length=54, null=True)),
                ('run', models.IntegerField(blank=True, null=True)),
                ('dv', models.CharField(blank=True, max_length=1, null=True)),
                ('estado', models.IntegerField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('secretaria_encargada', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Gestion_viajes.secretaria')),
            ],
        ),
        migrations.CreateModel(
            name='GaleriaDocumentosTaxista',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='documentos/')),
                ('estado', models.IntegerField(blank=True, null=True)),
                ('vencimiento', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('dueño', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Gestion_viajes.taxista')),
            ],
        ),
        migrations.AddField(
            model_name='ruta',
            name='conductor',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Gestion_viajes.taxista'),
        ),
    ]
