# Generated by Django 3.1.14 on 2023-12-06 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion_viajes', '0020_auto_20231205_1821'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tipostarifa',
            old_name='tipo',
            new_name='convenio',
        ),
        migrations.AlterField(
            model_name='tarifa',
            name='monto_tarifa',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
