# Generated by Django 3.1.14 on 2023-12-14 21:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion_viajes', '0022_auto_20231206_1614'),
    ]

    operations = [
        migrations.CreateModel(
            name='Convenio',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('monto', models.FloatField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='tipostarifa',
            name='convenio',
        ),
        migrations.AddField(
            model_name='tarifa',
            name='nombre',
            field=models.CharField(blank=True, max_length=54, null=True),
        ),
        migrations.AddField(
            model_name='tarifa',
            name='convenio',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Gestion_viajes.convenio'),
        ),
    ]
