# Generated by Django 3.1.14 on 2023-12-15 01:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion_viajes', '0023_auto_20231214_1859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galeriadocumentostaxista',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='documentos_taxista/'),
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('patente', models.CharField(blank=True, max_length=6, null=True)),
                ('estado', models.IntegerField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('conductor', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Gestion_viajes.taxista')),
            ],
        ),
        migrations.CreateModel(
            name='GaleriaDocumentosVehiculo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='documentos_vehiculo/')),
                ('estado', models.IntegerField(blank=True, null=True)),
                ('vencimiento', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('dueño', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Gestion_viajes.taxista')),
            ],
        ),
    ]
