# Generated by Django 3.1.14 on 2024-01-02 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion_viajes', '0024_auto_20231214_2215'),
    ]

    operations = [
        migrations.AddField(
            model_name='secretaria',
            name='apellido_m',
            field=models.CharField(blank=True, max_length=54, null=True),
        ),
        migrations.AddField(
            model_name='secretaria',
            name='apellido_p',
            field=models.CharField(blank=True, max_length=54, null=True),
        ),
        migrations.AddField(
            model_name='secretaria',
            name='dv',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='secretaria',
            name='edad',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='secretaria',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='secretaria',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='secretaria',
            name='genero',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='secretaria',
            name='nombre',
            field=models.CharField(blank=True, max_length=54, null=True),
        ),
        migrations.AddField(
            model_name='secretaria',
            name='nombre_usu',
            field=models.CharField(blank=True, max_length=54, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='secretaria',
            name='password',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='secretaria',
            name='prefijo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Gestion_viajes.prefijospais'),
        ),
        migrations.AddField(
            model_name='secretaria',
            name='run',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='secretaria',
            name='telefono',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='secretaria',
            name='tipo',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
