# Generated by Django 3.1.14 on 2024-01-08 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion_viajes', '0026_reserva_reservante'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='plazas_disponibles',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
