# Generated by Django 3.1.14 on 2024-01-08 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion_viajes', '0027_reserva_plazas_disponibles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserva',
            name='plazas_disponibles',
        ),
        migrations.AddField(
            model_name='ruta',
            name='plazas_disponibles',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
