# Generated by Django 3.1.14 on 2024-01-08 07:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion_viajes', '0028_auto_20240108_0406'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='ruta_asociada',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Gestion_viajes.ruta'),
        ),
    ]
